# Generated by Django 3.2.3 on 2021-05-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='libros',
            new_name='libro',
        ),
    ]
